- name: Force Handlers/ Dependency Task IOS Playbook
  hosts: iosxe1.lab.example.com
  gather_facts: false
  force_handlers: true
  tasks:
    - name: Change Description for GiGabit Ethernet 1
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1
            description: "First NIC 11"
      notify:
        - save the device
        - GE1 Changed

    - name: Print Non Existed Variable to fail task
      ansible.builtin.debug:
        msg: "{{ wewe }}"

    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        state: present
        text: "Testing Login Banner Again"
      notify:
        - Banner Changed
        - save the device

  handlers:
    - name: Extra Handlers
      ansible.builtin.debug:
        msg: "Just No presence"

    - name: Banner Changed
      ansible.builtin.debug:
        msg: "Banner Changes Done"

    - name:  GE1 Changed
      ansible.builtin.debug:
        msg: "GE1 Changes Done"

    - name: save the device
      cisco.ios.ios_config:
        save_when: always
