- name: Ignore Errors Playbook
  hosts: iosxe1.lab.example.com
  gather_facts: false
  tasks:
    - name: Change Description for GiGabit Ethernet 1
      cisco.ios.ios_interfaces:
        config:
          - name: GigabitEthernet1111
            description: "First NIC 11"
      ignore_errors: true

    - name: Configure the login banner
      cisco.ios.ios_banner:
        banner: login
        state: present
        text: "Testing Login Banner Again"

    - name: save the device
      cisco.ios.ios_config:
        save_when: always
