---
# handlers file for cisco_prerequisites

- name: cisco_banner_changed
  ansible.builtin.debug:
    msg: "{{ cisco_prerequisites_banner }} Banner changed for {{ inventory_hostname}}"

- name: cisco_user_created
  ansible.builtin.debug:
    msg: "{{ cisco_prerequisites_user }} created successfully on {{ inventory_hostname}}"

- name: device_info_collected
  ansible.builtin.debug:
    msg: "{{ inventory_hostname }} info collected in /tmp/{{ inventory_hostname }}_facts.txt"
