---
# defaults file for cisco_prerequisites
cisco_prerequisites_banner: login
cisco_prerequisites_banner_text: "Hello Banner for Device"
cisco_prerequisites_user: mattias
cisco_prerequisites_password: redhat123
