---
# tasks file for cisco_config

- name: Change Description for {{ cisco_config_nic1 }}
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ cisco_config_nic1 }}"
        description: "{{ cisco_config_desc1 }}"
  notify:
    - GE1 Changed
    - save the device config

- name: Change Description for {{ cisco_config_nic2 }}
  cisco.ios.ios_interfaces:
    config:
      - name: "{{ cisco_config_nic2 }}"
        description: "{{ cisco_config_desc2 }}"
  notify:
    - GE2 Changed
    - save the device config
