---
# handlers file for cisco_config

- name:  GE1 Changed
  ansible.builtin.debug:
    msg: "GE1 Changes Done"
   
- name:  GE2 Changed
  ansible.builtin.debug:
    msg: "GE2 Changes Done"
    
- name: save the device config
  cisco.ios.ios_config:
    save_when: always

